// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7aZbzOgq1Hiss1zx5Tkcnr721LKUN4ao',
    appId: '1:490173185810:web:cc792f5dff831609e9bdcb',
    messagingSenderId: '490173185810',
    projectId: 'eraa-auth',
    authDomain: 'eraa-auth.firebaseapp.com',
    storageBucket: 'eraa-auth.appspot.com',
    measurementId: 'G-246NJJL3X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHjz0MKtzEZrnr4YpSc_WE_KlWiQdvOQ',
    appId: '1:490173185810:android:a95b9edcfd29ef15e9bdcb',
    messagingSenderId: '490173185810',
    projectId: 'eraa-auth',
    storageBucket: 'eraa-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFGnsMaMMl7Mg9ItBPqXc_Or9ACDxh_PU',
    appId: '1:490173185810:ios:d182702e5f4172fce9bdcb',
    messagingSenderId: '490173185810',
    projectId: 'eraa-auth',
    storageBucket: 'eraa-auth.appspot.com',
    iosClientId: '490173185810-h6us5sp847tbsm6linvn91gu6vaoil75.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoShared',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFGnsMaMMl7Mg9ItBPqXc_Or9ACDxh_PU',
    appId: '1:490173185810:ios:d182702e5f4172fce9bdcb',
    messagingSenderId: '490173185810',
    projectId: 'eraa-auth',
    storageBucket: 'eraa-auth.appspot.com',
    iosClientId: '490173185810-h6us5sp847tbsm6linvn91gu6vaoil75.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoShared',
  );
}
